module.exports = {
  languages: [
    { name: "python", lang_code: "pyt" },
    { name: "node js", lang_code: "nod" },
    { name: "php", lang_code: "php" },
  ],
  authors: [
    {
      name: "Olivia Thomson",
      language: "pyt",
      author_code: "AUTH001",
    },
    {
      name: "Olivia Thomson",
      language: "php",
      author_code: "AUTH001",
    },
    {
      name: "Liam Johnson",
      language: "nod",
      author_code: "AUTH003",
    },
    {
      name: "Emma Davis",
      language: "php",
      author_code: "AUTH004",
    },
    {
      name: "Noah Martinez",
      language: "pyt",
      author_code: "AUTH005",
    },
    {
      name: "Ava Brown",
      language: "nod",
      author_code: "AUTH006",
    },
    {
      name: "William Garcia",
      language: "php",
      author_code: "AUTH007",
    },
    {
      name: "William Garcia",
      language: "nod",
      author_code: "AUTH007",
    },
    {
      name: "Sophia Wilson",
      language: "pyt",
      author_code: "AUTH009",
    },
    {
      name: "James Anderson",
      language: "nod",
      author_code: "AUTH010",
    },
    {
      name: "Isabella Thomas",
      language: "php",
      author_code: "AUTH011",
    },
    {
      name: "Benjamin Harris",
      language: "pyt",
      author_code: "AUTH012",
    },
    {
      name: "Benjamin Harris",
      language: "php",
      author_code: "AUTH012",
    },
    {
      name: "Benjamin Harris",
      language: "nod",
      author_code: "AUTH012",
    },
  ],
  courses: [
    {
      name: "Introduction to Node.js",
      author_code: "AUTH003",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Advanced Python Programming",
      author_code: "AUTH001",
      lang_code: "pyt",
      paid: false,
    },
    {
      name: "PHP for Beginners",
      author_code: "AUTH004",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Mastering Node.js",
      author_code: "AUTH006",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "Python Data Science",
      author_code: "AUTH012",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Full-Stack Development with PHP",
      author_code: "AUTH007",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Node.js API Development",
      author_code: "AUTH012",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Python for Data Analysis",
      author_code: "AUTH005",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "PHP and MySQL",
      author_code: "AUTH012",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Node.js and Express.js",
      author_code: "AUTH010",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Python Web Development",
      author_code: "AUTH009",
      lang_code: "pyt",
      paid: false,
    },
    {
      name: "Advanced PHP Techniques",
      author_code: "AUTH011",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Node.js with MongoDB",
      author_code: "AUTH007",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "PHP Automation Scripts",
      author_code: "AUTH001",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Building Websites with PHP",
      author_code: "AUTH004",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Node.js for Beginners",
      author_code: "AUTH006",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Python Machine Learning",
      author_code: "AUTH001",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "PHP Object-Oriented Programming",
      author_code: "AUTH012",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Node.js Real-Time Applications",
      author_code: "AUTH003",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Python for Web Scraping",
      author_code: "AUTH009",
      lang_code: "pyt",
      paid: false,
    },
    {
      name: "PHP Debugging Techniques",
      author_code: "AUTH007",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Node.js Security Best Practices",
      author_code: "AUTH012",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "Python GUI Development",
      author_code: "AUTH012",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Advanced Node.js",
      author_code: "AUTH010",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "PHP Frameworks Comparison",
      author_code: "AUTH001",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Introduction to Python",
      author_code: "AUTH005",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Node.js and Angular",
      author_code: "AUTH007",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "PHP Security Best Practices",
      author_code: "AUTH011",
      lang_code: "php",
      paid: true,
    },
    {
      name: "PHP Networking",
      author_code: "AUTH012",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Node.js and React",
      author_code: "AUTH006",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "PHP for E-commerce",
      author_code: "AUTH007",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Python Scripting Essentials",
      author_code: "AUTH001",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Node.js Deployment",
      author_code: "AUTH003",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "Introduction to PHP",
      author_code: "AUTH004",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Advanced Python Data Structures",
      author_code: "AUTH012",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Node.js and TypeScript",
      author_code: "AUTH012",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "Python for Automation",
      author_code: "AUTH005",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "PHP Template with Twig",
      author_code: "AUTH001",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Node.js and Vue.js",
      author_code: "AUTH010",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "Python Data Visualization",
      author_code: "AUTH009",
      lang_code: "pyt",
      paid: true,
    },
    {
      name: "Building RESTful APIs with Node.js",
      author_code: "AUTH007",
      lang_code: "nod",
      paid: false,
    },
    {
      name: "PHP Performance Optimization",
      author_code: "AUTH012",
      lang_code: "php",
      paid: true,
    },
    {
      name: "PHP for Web Development",
      author_code: "AUTH011",
      lang_code: "php",
      paid: false,
    },
    {
      name: "Introduction to Node.js Development",
      author_code: "AUTH006",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "PHP for Content Management",
      author_code: "AUTH004",
      lang_code: "php",
      paid: true,
    },
    {
      name: "Python Libraries Overview",
      author_code: "AUTH001",
      lang_code: "pyt",
      paid: false,
    },
    {
      name: "Advanced Node.js Patterns",
      author_code: "AUTH003",
      lang_code: "nod",
      paid: true,
    },
    {
      name: "PHP Integration Techniques",
      author_code: "AUTH007",
      lang_code: "php",
      paid: true,
    },
  ],
};
